/// <summary>
/// An enumeration of the audio clip names
/// </summary>
public enum AudioClipName
{
    None,
    mus_Core,
    mus_slow,
    mus_sweetlysoft,
    mus_lost,
    sfx_player_ShovelSwing,
    sfx_player_Walking,
    sfx_player_eatitem,
    sfx_player_harvestplant,
    sfx_player_rangedattack,
    sfx_player_shoveldigging,
    sfx_enemy_thornattack,
    sfx_enemy_thornidle,
    sfx_enemy_thornwalk,
    sfx_enemy_thornhit,
    sfx_enemy_pinetree_explode,
    sfx_enemy_pinetree_throw,
    sfx_enemy_pouncer_idle,
    sfx_enemy_pouncer_scurring,
    sfx_enemy_slimewalk,
    sfx_enemy_slimehit,
    sfx_enemy_stalagopede_dig,
    sfx_enemy_stalagopede_headground,
    sfx_enemy_treetrap_attack,
    sfx_Ui_grab,
    sfx_Ui_press,
    sfx_Ui_switch,
    sfx_player_hit,
    sfx_enemy_pouncer_hit,
    sfx_Boss_Burrow_Spike,
    sfx_Boss_Fire_Wall,
    sfx_CorpseTreeBossIdle,
    sfx_ant_walk,
    sfx_ant_swirl,
    sfx_firelog_fire,
    sfx_firelog_idle,
    mus_boss2,
    mus_wander,
    mus_boss3,
    mus_missing,
    Sfx_Corpsebloom_Fire,
    Sfx_Corpsebloom_GasCloud,
    Sfx_Corpsebloom_Idle,
    sfx_GasCloud,
    Sfx_CordycepsFire,

}
